window.MYTHOS_PACK_01 = {
entries: [
{id:"ANA-001",culture:"Pre-Pottery Neolithic Anatolia",category:"Monumental archaeology",title:"Göbekli Tepe was built by farming-era urbanites",status:"Contradicted",confidence:.94,date:"9600–8200 BCE",era:"Ancient",claim:"The monument complex was constructed only after fully developed agriculture and cities existed.",evidence:"UNESCO identifies the monumental enclosures as built by hunter-gatherer communities in the Pre-Pottery Neolithic, before the mature urban societies of later periods.",counter:"The exact economic organization of the builders and the site's relationship to nearby early farming communities remain active research questions.",meaning:"Monumental architecture does not require a later urban civilization; the chronology matters.",sources:[["UNESCO — Göbekli Tepe","https://whc.unesco.org/en/list/1572"]]},
{id:"ANA-002",culture:"Pre-Pottery Neolithic Anatolia",category:"Extraterrestrial claim",title:"Göbekli Tepe proves extraterrestrial construction",status:"Undetermined",confidence:.01,date:"modern claim",era:"Present",claim:"The geometry or iconography of Göbekli Tepe demonstrates intervention by extraterrestrial builders.",evidence:"The site is archaeologically documented as a human-built monument complex with quarrying, carving and construction evidence.",counter:"No independent archaeological, biological or technological evidence establishes extraterrestrial involvement.",meaning:"The site is extraordinary human archaeology without requiring an extraordinary non-human explanation.",sources:[["UNESCO — Göbekli Tepe","https://whc.unesco.org/en/list/1572"]]},
{id:"ANA-003",culture:"Neolithic Anatolia",category:"Settlement",title:"Çatalhöyük was a long-lived settled community with symbolic traditions",status:"Corroborated",confidence:.97,date:"7400–5200 BCE",era:"Ancient",claim:"Çatalhöyük documents sustained sedentary life, agriculture and symbolic practice over many centuries.",evidence:"UNESCO reports 18 Neolithic occupation levels, wall paintings, reliefs, sculptures, burials and a dense roof-access settlement maintained for more than 2,000 years.",counter:"Interpretations of social hierarchy, religion and household organization remain debated.",meaning:"The material record can reconstruct social complexity without relying on later written myths.",sources:[["UNESCO — Çatalhöyük","https://whc.unesco.org/en/list/1405"]]},
{id:"ANA-004",culture:"Ancient Southern Africa",category:"Symbolic behavior",title:"Homo sapiens used deliberate abstract graphic marks by ~73,000 years ago",status:"Corroborated",confidence:.98,date:"~73,000 years ago",era:"Ancient",claim:"People at Blombos Cave intentionally produced an abstract ochre drawing.",evidence:"Microscopic and chemical analysis identified an intentional cross-hatched design made with an ochre crayon on a silcrete flake.",counter:"The meaning of the abstract symbol cannot presently be recovered.",meaning:"Intentional symbolism is demonstrable even when the symbolic vocabulary is lost.",sources:[["Nature — Blombos Cave drawing","https://www.nature.com/articles/s41586-018-0514-3"]]},
{id:"ANA-005",culture:"Indus / Harappan",category:"Writing",title:"The Indus script has been fully deciphered",status:"Contradicted",confidence:.99,date:"c. 2600–1900 BCE",era:"Ancient",claim:"A generally accepted decipherment of the Indus script exists.",evidence:"Museum and archaeological references continue to describe the Indus script as undeciphered; inscriptions are generally short and the underlying language remains unresolved.",counter:"Individual proposed readings exist, but no decipherment has achieved broad scholarly acceptance.",meaning:"A confident online translation is not equivalent to a demonstrated decipherment.",sources:[["British Museum — Indus Valley Civilisation","https://www.britishmuseum.org/collection/term/x46239"],["Metropolitan Museum — Indus seal","https://www.metmuseum.org/art/collection/search/324062"]]},
{id:"ANA-006",culture:"Indus / Harappan",category:"Trade",title:"Harappan communities maintained long-distance exchange networks",status:"Corroborated",confidence:.96,date:"c. 2600–1900 BCE",era:"Ancient",claim:"Indus communities participated in extensive trade networks reaching the Persian Gulf and Mesopotamia.",evidence:"Archaeological seals and textual evidence document connections involving the Indus region, Gulf settlements and Mesopotamia; Harappan seal types occur outside the core region.",counter:"Individual voyages, merchants and routes are reconstructed probabilistically from archaeological distributions.",meaning:"Trade networks provide a real mechanism for cultural transmission without assuming one common civilization.",sources:[["British Museum — Indus stamp seal","https://www.britishmuseum.org/collection/object/W_1932-1008-178"]]},
{id:"ANA-007",culture:"Ancient Egypt",category:"Pyramid labor",title:"The Giza pyramids were built by an army of slaves",status:"Contradicted",confidence:.93,date:"Old Kingdom",era:"Ancient",claim:"The main pyramid workforce consisted primarily of enslaved laborers.",evidence:"Archaeological evidence from the Giza workers' settlement and tombs indicates organized teams of skilled and manual workers, provisioning and institutional support rather than the simple slave-army model.",counter:"Forced labor, obligations and unequal status existed in ancient societies, so 'free workers' is also too simple as a universal description.",meaning:"The labor system should be reconstructed from archaeology rather than inherited from later retellings.",sources:[["Smithsonian Magazine — Pyramid builders","https://www.smithsonianmag.com/history/35-who-made-a-difference-mark-lehner-114734077/"]]},
{id:"ANA-008",culture:"Pre-Columbian North America",category:"Urban archaeology",title:"North America had no major pre-Columbian cities",status:"Contradicted",confidence:.99,date:"c. 800–1400 CE",era:"Ancient",claim:"Large organized urban settlements did not exist north of Mexico before European arrival.",evidence:"Cahokia was the largest pre-Columbian settlement north of Mexico, covering roughly 1,600 hectares with numerous mounds and a peak population estimated in the thousands to tens of thousands.",counter:"Population estimates remain model-dependent and the settlement was later abandoned.",meaning:"Absence from colonial narratives is not evidence that a complex settlement did not exist.",sources:[["UNESCO — Cahokia Mounds","https://whc.unesco.org/en/list/198"]]},
{id:"ANA-009",culture:"Southern Africa",category:"Archaeology / historical identity",title:"Great Zimbabwe was built by a foreign lost civilization",status:"Contradicted",confidence:.98,date:"11th–15th centuries CE",era:"Ancient",claim:"The monumental city could not have been built by local African societies and therefore must have been Egyptian, Phoenician, Arab or otherwise foreign.",evidence:"Archaeology identifies Great Zimbabwe as a major center of the Shona/Bantu world, built between about 1100 and 1450 CE and integrated into regional trade.",counter:"External trade contacts were real, but trade does not transfer authorship of the monumental settlement to foreigners.",meaning:"The case is a powerful example of an archaeological fact being distorted by a false attribution of authorship.",sources:[["UNESCO — Great Zimbabwe","https://whc.unesco.org/en/list/364"]]},
{id:"ANA-010",culture:"Nasca",category:"Geoglyph interpretation",title:"The Nasca Lines were aircraft runways for ancient visitors",status:"Undetermined",confidence:.02,date:"500 BCE–500 CE",era:"Ancient",claim:"The geoglyphs were constructed as physical landing strips for extraterrestrial spacecraft.",evidence:"The lines and figures are archaeologically documented as a long-lived symbolic and ritual landscape; UNESCO describes likely ritual and astronomical functions.",counter:"Their precise local functions varied and remain studied, but no material evidence establishes spacecraft or extraterrestrial construction.",meaning:"An enigmatic landscape is not evidence for the most exotic available explanation.",sources:[["UNESCO — Nasca and Palpa","https://whc.unesco.org/en/list/700"]]},
{id:"MED-001",culture:"Great Zimbabwe",category:"Political memory",title:"European claims about Great Zimbabwe's builders were shaped by colonial-era attribution",status:"Historically attested",confidence:.94,date:"19th–20th centuries",era:"Middle",claim:"Colonial-era narratives attributed Great Zimbabwe to outsiders despite archaeological evidence for local African construction.",evidence:"The site was historically associated with legends such as the Queen of Sheba while modern archaeology identifies its construction with Shona societies.",counter:"The medieval site's actual external trade connections should not be dismissed merely because later authors misattributed its builders.",meaning:"MYTHOS records not only old myths but the history of how modern authorities reinterpreted physical evidence.",sources:[["UNESCO — Great Zimbabwe","https://whc.unesco.org/en/list/364"]]},
{id:"MED-002",culture:"Andean / Pre-Inca",category:"Medicine",title:"Prehistoric Peruvian trepanation was practiced with no survival",status:"Contradicted",confidence:.98,date:"400 BCE–1500 CE",era:"Middle",claim:"Ancient trepanation was uniformly fatal because prehistoric surgeons lacked effective technique.",evidence:"Analysis of more than 800 trepanned Peruvian crania found long-term survival rates increasing substantially through time, reaching roughly 75–83% in the Inca-period sample.",counter:"Survival rates vary by period, region, technique and selection of recovered remains.",meaning:"The physical record can reveal sophisticated empirical medical practice without requiring modern biomedical theory.",sources:[["PubMed — Prehistoric Peru trepanation outcomes","https://pubmed.ncbi.nlm.nih.gov/29604358/"]]},
{id:"MED-003",culture:"Viking North Atlantic",category:"Navigation technology",title:"Viking sunstone navigation is a demonstrated historical fact",status:"Plausible",confidence:.68,date:"c. 900–1200 CE",era:"Middle",claim:"Norse sailors used birefringent crystals to determine the Sun's direction under cloudy or twilight conditions.",evidence:"Experimental studies show Iceland spar could support sky-polarimetric navigation and Viking literary sources describe a 'sunstone'.",counter:"No surviving Viking navigation manual unambiguously identifies the crystal, and the archaeological record does not establish routine use.",meaning:"Physical feasibility plus textual hints make the technique plausible, but historical use remains a distinct claim.",sources:[["Royal Society — Viking sunstone","https://royalsociety.org/news/2011/mysteries-of-the-viking-sunstone/"],["Royal Society / PMC experimental study","https://pmc.ncbi.nlm.nih.gov/articles/PMC5936938/"]]},
{id:"MED-004",culture:"Late Bronze Age / Europe",category:"Population change",title:"Ancient plague contributed to major Neolithic demographic change in Europe",status:"Partially supported",confidence:.79,date:"5300–4900 BP",era:"Middle",claim:"Yersinia pestis was a major driver of the Neolithic population decline across large parts of Europe.",evidence:"Ancient genomes document repeated plague infection across generations of Neolithic farmers, including evidence from Britain around 4000 years ago.",counter:"The relative roles of plague, climate, food systems, migration and social restructuring remain debated.",meaning:"Pathogens belong directly inside explanations of myth, migration and social transformation.",sources:[["Nature — Repeated plague infections among Neolithic farmers","https://www.nature.com/articles/s41586-024-07651-2"],["Nature Communications — Yersinia pestis in Britain","https://www.nature.com/articles/s41467-023-38393-w"]]}
],
deepTime: [
{id:"DEEP-010",title:"Denisova Cave was occupied by Denisovans, Neanderthals and modern humans",status:"Corroborated",confidence:.99,window:"last ~300,000 years",summary:"Chronology, archaeology, hominin fossils and sediment DNA reconstruct a cave occupied by multiple human lineages across several glacial cycles.",source:"https://www.nature.com/articles/s41467-025-60140-6"},
{id:"DEEP-011",title:"A Neanderthal–Denisovan offspring is documented",status:"Corroborated",confidence:.99,window:"Pleistocene",summary:"Denisova Cave produced a bone fragment whose genome showed one Neanderthal parent and one Denisovan parent.",source:"https://www.nature.com/articles/s41467-025-60140-6"},
{id:"DEEP-012",title:"Denisovans left an archaeological record extending beyond Denisova Cave",status:"Corroborated",confidence:.89,window:"Pleistocene",summary:"Recent research combines fossils, proteins, archaeology and genetics to identify Denisovan presence beyond the original Siberian cave record.",source:"https://www.nature.com/articles/d41586-026-02810-z"},
{id:"DEEP-013",title:"Narrative image-making existed by at least 51,200 years ago in Sulawesi",status:"Corroborated",confidence:.99,window:"51,200 years ago",summary:"U-series laser-ablation dating places a figurative scene of human-like beings and animals in Sulawesi at 51,200 years ago, making it the oldest currently known surviving narrative cave art.",source:"https://www.nature.com/articles/s41586-024-07541-7"},
{id:"DEEP-014",title:"Mid-Middle-Palaeolithic groups shared complex symbolic behaviors in the Levant",status:"Corroborated",confidence:.91,window:"~130,000–80,000 years ago",summary:"Tinshemet Cave evidence includes burials, ochre and lithic traditions shared across multiple Homo groups in the Levant.",source:"https://www.nature.com/articles/s41562-025-02110-y"},
{id:"DEEP-015",title:"Neanderthals disappeared because of one single cause",status:"Undetermined",confidence:.12,window:"~45,000–40,000 BP",summary:"Climate stress, demographic conditions, interaction with Homo sapiens and regional ecological changes are all discussed; current evidence does not isolate a single universal cause.",source:"https://www.nature.com/articles/s43247-026-03960-8"},
{id:"DEEP-016",title:"The steppe migration altered the ancestry of later European populations",status:"Corroborated",confidence:.96,window:"8,000–3,000 years ago",summary:"Ancient DNA identifies major population movements from the Eurasian steppe that reshaped the ancestry of later European populations.",source:"https://www.nature.com/articles/nature14317"}
],
technologies: [
{id:"TECH-V-008",title:"Roman concrete construction used deliberate hot mixing",kind:"Recovered technique",status:"Corroborated",confidence:.96,summary:"A preserved Pompeian construction site provides direct material evidence that quicklime was pre-mixed with dry pozzolan before water was added.",source:"https://www.nature.com/articles/s41467-025-66634-7"},
{id:"TECH-V-009",title:"The Antikythera Mechanism modeled astronomical cycles mechanically",kind:"Recovered artifact",status:"Corroborated",confidence:.99,summary:"Inscribed gearing and reconstructed mechanisms demonstrate mechanical treatment of lunar, solar and eclipse cycles in the Hellenistic world.",source:"https://www.nature.com/articles/nature05357"},
{id:"TECH-V-010",title:"The Baghdad Battery's historical purpose is established",kind:"Disputed interpretation",status:"Undetermined",confidence:.40,summary:"The artifact can be made to produce an electrical potential in laboratory arrangements, but archaeological context does not establish that electricity was its historical purpose.",source:"https://www.history.com/articles/baghdad-battery"},
{id:"TECH-V-011",title:"Historical Damascus steel can contain nanoscale structures",kind:"Recovered material knowledge",status:"Corroborated",confidence:.92,summary:"Materials analysis found carbon nanotubes and cementite nanowires in a historical Damascus sabre, illustrating complex microstructures produced by empirical metallurgy.",source:"https://www.nature.com/articles/444286a"}
],
tricksters: [
{id:"TRICK-ARCH-006",kind:"Fabricated document",title:"Protocols of the Elders of Zion",mechanism:"Forged minutes / plagiarism / conspiracy propaganda",status:"Contradicted",confidence:.99,era:"Present",summary:"The purported secret meeting minutes were fabricated and drew substantially on earlier works; investigators demonstrated the fraud by textual comparison.",sources:["https://encyclopedia.ushmm.org/content/en/article/protocols-of-the-elders-of-zion"]},
{id:"TRICK-ARCH-007",kind:"Scientific hoax",title:"Piltdown Man",mechanism:"Manipulated fossil evidence",status:"Contradicted",confidence:.99,era:"Present",summary:"A composite and manipulated specimen was treated as evidence for an early human ancestor until forensic examination exposed the fraud.",sources:["https://www.nhm.ac.uk/our-science/services/collections/palaeontology/palaeoanthropology.html"]},
{id:"TRICK-ARCH-008",kind:"Antiquarian forgery",title:"De Situ Britanniae",mechanism:"Fabricated ancient source",status:"Contradicted",confidence:.97,era:"Middle",summary:"A purported ancient source for Britain entered historical scholarship as a manuscript and was later exposed as an elaborate forgery.",sources:["https://academic.oup.com/edinburgh-scholarship-online/book/38048/chapter-abstract/332622203"]},
{id:"TRICK-ARCH-009",kind:"Constructed ancient history",title:"Atlantis — Plato",mechanism:"Historical-looking narrative embedded in philosophical argument",status:"Plausible",confidence:.91,era:"Ancient",summary:"The story's detailed pseudo-historical provenance and usefulness inside Plato's philosophical program make deliberate construction a strong scholarly interpretation, without requiring a verdict about Plato's private intentions.",sources:["https://www.cambridge.org/core/books/abs/platos-natural-philosophy/status-of-the-atlantis-story/2306779EF1D84DF6028498C3661DED6B","https://www.cambridge.org/core/journals/journal-of-hellenic-studies/article/abs/designer-history-platos-atlantis-story-and-fourthcentury-ideology/828B7BB540EB710BF9F9D6E3840F2456"]}
],
correlations: [
{id:"HERO-009",pattern:"Culture hero acquires / steals fire → humanity gains a transformative technology",motifs:["fire","theft","culture hero","technology","benefit"],stories:["Prometheus","Māui","Raven traditions","Coyote traditions"],relation:"possible",strength:77,analysis:"Fire theft is an unusually widespread culture-hero motif, but the stories have different structures and histories. Fire itself is a universal human technology, so convergence is a serious alternative to common descent.",evidence:"Comparative mythology can identify the recurring motif; establishing common ancestry requires language, chronology and contact evidence.",sources:[]},
{id:"HERO-010",pattern:"World tree / cosmic axis connecting multiple realms",motifs:["world tree","axis mundi","upper world","underworld","cosmos"],stories:["Yggdrasil","Mesoamerican world trees","Siberian cosmologies","South Asian cosmic-tree traditions"],relation:"parallel",strength:58,analysis:"The axis-between-realms pattern is widespread, but its generic relationship to trees, mountains and vertical cosmology makes independent convergence particularly plausible.",evidence:"A shared image is weaker evidence than a rare ordered sequence with a plausible transmission route.",sources:[]},
{id:"HERO-011",pattern:"Hero crosses threshold → confronts guardian → returns transformed",motifs:["threshold","guardian","ordeal","return","transformation"],stories:["Inanna","Odysseus","Herakles","shamanic journey traditions"],relation:"strong",strength:79,analysis:"The sequence recurs across descent and initiation stories, but the individual theological functions differ. MYTHOS records the structural recurrence without treating it as proof of one original narrative.",evidence:"Comparative work on underworld journeys and heroic structures supports motif-level comparison while cautioning against flattening distinct traditions.",sources:[["Cambridge — Myths of the Underworld Journey","https://assets.cambridge.org/052183/4341/excerpt/0521834341_excerpt.htm"]]}
]
};