const records=[
{name:"Peganum harmala",latin:"Syrian rue",kind:"entheogen high-risk",desc:"β-carboline alkaloids including harmine and harmaline. Documented MAO-A inhibition makes interaction and toxicity research central to the record.",tags:["harmine","harmaline","MAO-A","ethnobotany"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Peganum+harmala",note:"Strong pharmacological mechanism; human safety and interaction evidence must be treated separately from traditional use."},
{name:"Banisteriopsis caapi",latin:"ayahuasca vine",kind:"entheogen",desc:"A traditional Amazonian preparation component containing β-carbolines. Record separately from DMT-containing admixture plants.",tags:["harmine","harmaline","ayahuasca","Amazonia"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Banisteriopsis+caapi",note:"Ethnographic and pharmacological literature is substantial; preparation and combination materially affect the pharmacology."},
{name:"Psychotria viridis",latin:"chacruna",kind:"entheogen",desc:"Traditional ayahuasca admixture plant associated with DMT. The record distinguishes plant chemistry from the combined ayahuasca preparation.",tags:["DMT","ayahuasca","ethnobotany"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Psychotria+viridis",note:"Do not infer effects of the complete preparation from an isolated constituent without accounting for route and MAO inhibition."},
{name:"Nymphaea caerulea",latin:"blue lotus",kind:"entheogen medicinal",desc:"Historically associated with Egyptian cultural use and modern reports of relaxation and altered experience. Human clinical evidence remains limited.",tags:["Nymphaea","Egypt","phenomenology"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Nymphaea+caerulea",note:"Commercial preparations vary substantially; experiential reports are not equivalent to controlled evidence."},
{name:"Nigella sativa",latin:"black seed",kind:"medicinal",desc:"Black seed/black cumin. Human trials investigate metabolic and cardiovascular markers; evidence quality varies by outcome.",tags:["thymoquinone","glucose","lipids","BP"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Nigella+sativa+systematic+review",note:"Promising signals, but heterogeneous preparations and generally limited trial quality constrain strong conclusions."},
{name:"Origanum species",latin:"oregano / carvacrol",kind:"medicinal",desc:"Carvacrol and related constituents have substantial experimental antimicrobial activity. Human evidence for oral oregano as treatment of infection is much weaker.",tags:["carvacrol","antimicrobial","phytochemistry"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=oregano+carvacrol+clinical",note:"In-vitro antimicrobial activity must not be silently upgraded into clinical antibiotic efficacy."},
{name:"Aged garlic extract",latin:"Allium sativum",kind:"medicinal",desc:"Long-aged garlic preparations have been studied for cardiovascular risk markers, including blood pressure and vascular measures.",tags:["S-allylcysteine","aged garlic","BP"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=aged+garlic+extract+randomized+trial",note:"20-month aging is a preparation technology associated with changed sulfur chemistry; it is not an oregano-oil property."},
{name:"Psilocybin mushrooms",latin:"Psilocybe spp.",kind:"fungi entheogen high-risk",desc:"A large modern research literature spans neuroimaging, phenomenology and controlled clinical studies, alongside extensive community trip-report archives.",tags:["psilocybin","phenomenology","mycology"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=psilocybin+systematic+review",note:"Species identification, potency variability, setting and mental-health context materially affect risk and interpretation."},
{name:"Salvia divinorum",latin:"diviner's sage",kind:"entheogen high-risk",desc:"Salvinorin A is a potent kappa-opioid receptor agonist producing a distinctive short-duration altered state.",tags:["salvinorin A","KOR","phenomenology"],source:"https://pubmed.ncbi.nlm.nih.gov/?term=Salvia+divinorum+salvinorin+A",note:"Distinct mechanism from classical serotonergic psychedelics; human evidence is comparatively sparse."}
];
const cards=document.querySelector("#cards"),search=document.querySelector("#search"),filter=document.querySelector("#filter");
function render(){const q=search.value.toLowerCase();const f=filter.value;cards.innerHTML=records.filter(r=>(f==="all"||r.kind.includes(f))&&[r.name,r.latin,r.desc,...r.tags].join(" ").toLowerCase().includes(q)).map(r=>`<article class="card"><span class="tag">${r.kind.toUpperCase()}</span><h3>${r.name}</h3><div class="latin">${r.latin}</div><p>${r.desc}</p><span class="badge">${r.note}</span><div class="bottom"><span class="tag">${r.tags.join(" · ")}</span><a href="${r.source}" target="_blank" rel="noreferrer">Sources ↗</a></div></article>`).join("")||'<p class="card">No records match that query.</p>'}
search.addEventListener("input",render);filter.addEventListener("change",render);render();